### ISSUE TITLE
How about later versions like 3.2.1?

### ISSUE THREAD

**Issue by dxxvi** [thesabbir/jquery-slim#2]

**Comment by joonas-fi** [comment]
Yes, you can configure Webpack to inject this slimmed version each time soneone uses the `jQuery` or `$` variable:

```
plugins: [
        new webpack.ProvidePlugin({
           jQuery: 'jquery/dist/jquery.slim.js',
           $: 'jquery/dist/jquery.slim.js',
       })
],
```

And in your `package.json` you can yourself decide which version of jQuery you are using.
